# Generated by Django 5.2.4 on 2025-07-20 21:53

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0002_delete_projectinquiry_remove_inquiry_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='summary',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
