# Generated by Django 5.2.4 on 2025-07-20 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0003_blog_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='namme',
            new_name='name',
        ),
    ]
