# Generated by Django 5.2.4 on 2025-07-28 14:09

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0005_blog_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=750)),
                ('image', models.ImageField(upload_to='field/')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('pdf', models.FileField(upload_to='documents/')),
                ('youtube_id', models.CharField(max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=750)),
                ('image', models.ImageField(upload_to='programming_language/')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
                ('pdf', models.FileField(upload_to='documents/')),
                ('youtube_id', models.CharField(max_length=20000)),
            ],
        ),
    ]
