# Generated by Django 5.2.4 on 2025-07-28 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0006_field_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='pdf',
        ),
        migrations.RemoveField(
            model_name='language',
            name='pdf',
        ),
    ]
