# Generated by Django 5.2.4 on 2025-07-28 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0007_remove_field_pdf_remove_language_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='image',
        ),
        migrations.RemoveField(
            model_name='language',
            name='image',
        ),
    ]
