# Generated by Django 5.2.4 on 2025-07-29 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0008_remove_field_image_remove_language_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='summary',
        ),
    ]
